// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djlmxjegclnlhjkorjxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbG14amVnY2xubGhqa29yanhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTEzMDcsImV4cCI6MjA2NTY2NzMwN30.AHT7g-geKaU2yOr7yu92QVLXio380Hwbw72ICFBHZtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);